/**
 * Build a custom Lucide icon bundle with only the icons used on the site.
 * Reads the full lucide.min.js UMD bundle, extracts needed icon data,
 * and generates a minimal replacement (~15-20KB vs 350KB).
 *
 * Usage: node scripts/build-icons.js
 */

const fs = require('fs');
const path = require('path');

// Load the full Lucide UMD bundle
const lucide = require('../src/assets/js/lucide-full.js');

// Map of data-lucide attribute values → PascalCase export names
// These are ALL icons used across the site (82 unique + 1 alias fix)
const iconMap = {
  'accessibility': 'Accessibility',
  'alert-circle': 'AlertCircle',
  'anchor': 'Anchor',
  'arrow-right': 'ArrowRight',
  'arrow-up-right': 'ArrowUpRight',
  'award': 'Award',
  'bar-chart-3': 'BarChart3',
  'beer': 'Beer',
  'bookmark': 'Bookmark',
  'book-open': 'BookOpen',
  'briefcase': 'Briefcase',
  'building-2': 'Building2',
  'calendar': 'Calendar',
  'car': 'Car',
  'check': 'Check',
  'check-circle': 'CheckCircle',
  'check-circle-2': 'CheckCircle2',
  'chevron-down': 'ChevronDown',
  'clock': 'Clock',
  'credit-card': 'CreditCard',
  'crown': 'Crown',
  'database': 'Database',
  'dollar-sign': 'DollarSign',
  'edit': 'Edit',
  'external-link': 'ExternalLink',
  'facebook': 'Facebook',
  'figma': 'Figma',
  'file-text': 'FileText',
  'frame': 'Frame',
  'globe': 'Globe',
  'hammer': 'Hammer',
  'hard-hat': 'HardHat',
  'headphones': 'Headphones',
  'heart': 'Heart',
  'heart-pulse': 'HeartPulse',
  'help-circle': 'HelpCircle',
  'home': 'Home',
  'layers': 'Layers',
  'layout': 'Layout',
  'lightbulb': 'Lightbulb',
  'linkedin': 'Linkedin',
  'mail': 'Mail',
  'map': 'Map',
  'map-pin': 'MapPin',
  'megaphone': 'Megaphone',
  'menu': 'Menu',
  'message-circle': 'MessageCircle',
  'monitor': 'Monitor',
  'moon': 'Moon',
  'mouse-pointer-click': 'MousePointerClick',
  'palette': 'Palette',
  'pen': 'Pen',
  'pen-tool': 'PenTool',
  'phone': 'Phone',
  'quote': 'Quote',
  'rocket': 'Rocket',
  'scale': 'Scale',
  'scissors': 'Scissors',
  'search': 'Search',
  'send': 'Send',
  'settings': 'Settings',
  'share-2': 'Share2',
  'shield': 'Shield',
  'shield-check': 'ShieldCheck',
  'ship': 'Ship',
  'shopping-bag': 'ShoppingBag',
  'shopping-cart': 'ShoppingCart',
  'sliders': 'Sliders',
  'smartphone': 'Smartphone',
  'star': 'Star',
  'store': 'Store',
  'sun': 'Sun',
  'target': 'Target',
  'tree-pine': 'TreePine',
  'trending-up': 'TrendingUp',
  'type': 'Type',
  'user-plus': 'UserPlus',
  'users': 'Users',
  'utensils': 'Utensils',
  'video': 'Video',
  'x': 'X',
  'zap': 'Zap',
  // "bridge" doesn't exist in Lucide — mapped to "building-2" as fallback
  'bridge': 'Building2',
};

// Build the icons object entries
const iconEntries = [];
const missing = [];

for (const [kebab, pascal] of Object.entries(iconMap)) {
  const data = lucide[pascal];
  if (data) {
    iconEntries.push(`"${pascal}":${JSON.stringify(data)}`);
  } else {
    missing.push(`${kebab} → ${pascal}`);
  }
}

if (missing.length) {
  console.warn('⚠ Missing icons:', missing);
}

// Generate the minimal bundle
const bundle = `/**
 * Custom Lucide Icons Bundle — ${Object.keys(iconMap).length} icons
 * Auto-generated by scripts/build-icons.js
 * Based on lucide v0.469.0
 */
(function(g){
"use strict";
var icons={${iconEntries.join(',')}};
function ce(t){
var e=document.createElementNS("http://www.w3.org/2000/svg",t[0]);
var a=t[1];for(var k in a)e.setAttribute(k,String(a[k]));
if(t[2])for(var i=0;i<t[2].length;i++)e.appendChild(ce(t[2][i]));
return e;
}
function pc(s){return s.replace(/(^|[-_])(\\w)/g,function(_,__,c){return c.toUpperCase()});}
g.lucide={
createIcons:function(o){
o=o||{};
var attr=o.nameAttr||"data-lucide";
var ext=o.attrs||{};
var src=o.icons||icons;
var els=document.querySelectorAll("["+attr+"]");
for(var i=0;i<els.length;i++){
var el=els[i];
var name=el.getAttribute(attr);
if(!name)continue;
var pn=pc(name);
var ic=src[pn];
if(!ic)continue;
var ea={};for(var j=0;j<el.attributes.length;j++){var at=el.attributes[j];ea[at.name]=at.value;}
var ma={};var da=ic[1];for(var k in da)ma[k]=da[k];
ma["data-lucide"]=name;
for(var k in ext)ma[k]=ext[k];
for(var k in ea)ma[k]=ea[k];
var cls=["lucide","lucide-"+name];
if(ea["class"])cls.push(ea["class"]);
if(ext["class"])cls.push(ext["class"]);
ma["class"]=cls.join(" ");
var svg=ce([ic[0],ma,ic[2]]);
el.parentNode.replaceChild(svg,el);
}
}
};
})(typeof globalThis!=="undefined"?globalThis:typeof window!=="undefined"?window:this);
`;

const outPath = path.join(__dirname, '..', 'src', 'assets', 'js', 'lucide.min.js');
fs.writeFileSync(outPath, bundle);

const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`✓ Generated custom Lucide bundle: ${sizeKB} KB (${Object.keys(iconMap).length} icons)`);
console.log(`  Saved to: ${outPath}`);
